### ISSUE TITLE
打包umd也支持一下吧

### ISSUE THREAD

**Issue by hans000** [zhangfisher/styledfc#1]

**Comment by zhangfisher** [comment]
以现在的生态一般`esm`就能满足要求了

特别是不太明白，`styledfc`支持`umd`,`iife`这些好象意义不大

好在重新构建一下成本也不高，就都支持一下

**Comment by hans000** [comment]
> 以现在的生态一般`esm`就能满足要求了
> 
> 特别是不太明白，`styledfc`支持`umd`,`iife`这些好象意义不大
> 
> 好在重新构建一下成本也不高，就都支持一下

现在的工程化当然一个esm就够了，但是有些特殊的需要可能会用到umd或者iife，通常都是以cdn的方式引入的，后者更能避免污染window

然后我看iife打出来的包有点大，把其他东西也打进了吧

**Comment by zhangfisher** [comment]
我看了下，`iife`打出来的包里面含了`react`，不知道为什么tsup已经指定了external=['react']了，但打包还是包含了react，所以比较大。

**Comment by hans000** [comment]
可能是哪里配置的有问题

**Comment by zhangfisher** [comment]
iife打包是在浏览器中直接使用`<script link>`导入的，所以意义不大
